In [1]:
#from __future__ import absolute_import, division, print_function, unicode_literals
from __future__ import absolute_import, division, print_function
import numpy as np
import tensorflow as tf
#import tensorflow.contrib.eager as tfe
import pandas as pd



### What is TensorFlow's Eager API ?

*Eager execution is an imperative, define-by-run interface where operations are
executed immediately as they are called from Python. This makes it easier to
get started with TensorFlow, and can make research and development more
intuitive. A vast majority of the TensorFlow API remains the same whether eager
execution is enabled or not. As a result, the exact same code that constructs
TensorFlow graphs (e.g. using the layers API) can be executed imperatively
by using eager execution. Conversely, most models written with Eager enabled
can be converted to a graph that can be further optimized and/or extracted
for deployment in production without changing code. - Rajat Monga*

More info: https://research.googleblog.com/2017/10/eager-execution-imperative-define-by.html

In [2]:
#this section needed to enable iteration over tensor flow dataset

# Set Eager API
print("Setting Eager mode...")
tf.enable_eager_execution()
tfe = tf.contrib.eager

Setting Eager mode...

For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
If you depend on functionality not listed there, please file an issue.



In [3]:
#loading a csv data file into a pandas data frame

In [4]:
test_file_path='mtcars.csv'

In [23]:
cars = pd.read_csv(test_file_path)
yv=cars['mpg'].to_numpy()
xv=cars['hp'].to_numpy()
cars.columns = ['car_names','mpg','cyl','disp', 'hp', 'drat', 'wt', 'qsec', 'vs', 'am', 'gear', 'carb']
cars.index = cars.car_names

In [24]:
print(type(xv))
print(yv)

<class 'pandas.core.series.Series'>
[21.  21.  22.8 21.4 18.7 18.1 14.3 24.4 22.8 19.2 17.8 16.4 17.3 15.2
 10.4 10.4 14.7 32.4 30.4 33.9 21.5 15.5 15.2 13.3 19.2 27.3 26.  30.4
 15.8 19.7 15.  21.4]


In [6]:
cars.dtypes

car_names     object
mpg          float64
cyl            int64
disp         float64
hp             int64
drat         float64
wt           float64
qsec         float64
vs             int64
am             int64
gear           int64
carb           int64
dtype: object

In [7]:
cars['car_names'] = pd.Categorical(cars['car_names'])
cars['car_names'] = cars.car_names.cat.codes

In [8]:
mpg = cars.pop('mpg')

In [16]:
print(mpg[3])
print(mpg)
mpg1=(cars['mpg'])

21.4
car_names
Mazda RX4              21.0
Mazda RX4 Wag          21.0
Datsun 710             22.8
Hornet 4 Drive         21.4
Hornet Sportabout      18.7
Valiant                18.1
Duster 360             14.3
Merc 240D              24.4
Merc 230               22.8
Merc 280               19.2
Merc 280C              17.8
Merc 450SE             16.4
Merc 450SL             17.3
Merc 450SLC            15.2
Cadillac Fleetwood     10.4
Lincoln Continental    10.4
Chrysler Imperial      14.7
Fiat 128               32.4
Honda Civic            30.4
Toyota Corolla         33.9
Toyota Corona          21.5
Dodge Challenger       15.5
AMC Javelin            15.2
Camaro Z28             13.3
Pontiac Firebird       19.2
Fiat X1-9              27.3
Porsche 914-2          26.0
Lotus Europa           30.4
Ford Pantera L         15.8
Ferrari Dino           19.7
Maserati Bora          15.0
Volvo 142E             21.4
Name: mpg, dtype: float64


KeyError: 'mpg'

In [9]:
#loading a pandas data frame into tensor frame
#https://www.tensorflow.org/beta/guide/data

In [87]:
dataset = tf.data.Dataset.from_tensor_slices((cars.values, mpg.values))

In [88]:
print(cars)

cars.head

                     car_names  cyl   disp   hp  drat     wt   qsec  vs  am  \
car_names                                                                     
Mazda RX4                   17    6  160.0  110  3.90  2.620  16.46   0   1   
Mazda RX4 Wag               18    6  160.0  110  3.90  2.875  17.02   0   1   
Datsun 710                   4    4  108.0   93  3.85  2.320  18.61   1   1   
Hornet 4 Drive              12    6  258.0  110  3.08  3.215  19.44   1   0   
Hornet Sportabout           13    8  360.0  175  3.15  3.440  17.02   0   0   
Valiant                     30    6  225.0  105  2.76  3.460  20.22   1   0   
Duster 360                   6    8  360.0  245  3.21  3.570  15.84   0   0   
Merc 240D                   20    4  146.7   62  3.69  3.190  20.00   1   0   
Merc 230                    19    4  140.8   95  3.92  3.150  22.90   1   0   
Merc 280                    21    6  167.6  123  3.92  3.440  18.30   1   0   
Merc 280C                   22    6  167.6  123  3.9

<bound method NDFrame.head of                      car_names  cyl   disp   hp  drat     wt   qsec  vs  am  \
car_names                                                                     
Mazda RX4                   17    6  160.0  110  3.90  2.620  16.46   0   1   
Mazda RX4 Wag               18    6  160.0  110  3.90  2.875  17.02   0   1   
Datsun 710                   4    4  108.0   93  3.85  2.320  18.61   1   1   
Hornet 4 Drive              12    6  258.0  110  3.08  3.215  19.44   1   0   
Hornet Sportabout           13    8  360.0  175  3.15  3.440  17.02   0   0   
Valiant                     30    6  225.0  105  2.76  3.460  20.22   1   0   
Duster 360                   6    8  360.0  245  3.21  3.570  15.84   0   0   
Merc 240D                   20    4  146.7   62  3.69  3.190  20.00   1   0   
Merc 230                    19    4  140.8   95  3.92  3.150  22.90   1   0   
Merc 280                    21    6  167.6  123  3.92  3.440  18.30   1   0   
Merc 280C             

In [89]:

d0=dataset.take(1)

print(d0.output_types)

print(d0.output_shapes)


(tf.float64, tf.float64)
(TensorShape([Dimension(11)]), TensorShape([]))


In [90]:
#get 11 items
for feat, targ in dataset.take(11):
  print ('Features: {}, Target: {}'.format(feat, targ))

print('here')


#get the 11th item
dsnew=dataset.skip(10)
for feat, targ in dsnew.take(1):
  print ('Features: {}, Target: {}'.format(feat, targ))

print(feat[1])

Features: [ 17.     6.   160.   110.     3.9    2.62  16.46   0.     1.     4.
   4.  ], Target: 21.0
Features: [ 18.      6.    160.    110.      3.9     2.875  17.02    0.      1.
   4.      4.   ], Target: 21.0
Features: [  4.     4.   108.    93.     3.85   2.32  18.61   1.     1.     4.
   1.  ], Target: 22.8
Features: [ 12.      6.    258.    110.      3.08    3.215  19.44    1.      0.
   3.      1.   ], Target: 21.4
Features: [ 13.     8.   360.   175.     3.15   3.44  17.02   0.     0.     3.
   2.  ], Target: 18.7
Features: [ 30.     6.   225.   105.     2.76   3.46  20.22   1.     0.     3.
   1.  ], Target: 18.1
Features: [  6.     8.   360.   245.     3.21   3.57  15.84   0.     0.     3.
   4.  ], Target: 14.3
Features: [ 20.     4.   146.7   62.     3.69   3.19  20.     1.     0.     4.
   2.  ], Target: 24.4
Features: [ 19.     4.   140.8   95.     3.92   3.15  22.9    1.     0.     4.
   2.  ], Target: 22.8
Features: [ 21.     6.   167.6  123.     3.92   3.44  18.3    

In [91]:
for batch in tfe.Iterator(dataset):
     print(batch)

(<tf.Tensor: id=2152, shape=(11,), dtype=float64, numpy=
array([ 17.  ,   6.  , 160.  , 110.  ,   3.9 ,   2.62,  16.46,   0.  ,
         1.  ,   4.  ,   4.  ])>, <tf.Tensor: id=2153, shape=(), dtype=float64, numpy=21.0>)
(<tf.Tensor: id=2156, shape=(11,), dtype=float64, numpy=
array([ 18.   ,   6.   , 160.   , 110.   ,   3.9  ,   2.875,  17.02 ,
         0.   ,   1.   ,   4.   ,   4.   ])>, <tf.Tensor: id=2157, shape=(), dtype=float64, numpy=21.0>)
(<tf.Tensor: id=2160, shape=(11,), dtype=float64, numpy=
array([  4.  ,   4.  , 108.  ,  93.  ,   3.85,   2.32,  18.61,   1.  ,
         1.  ,   4.  ,   1.  ])>, <tf.Tensor: id=2161, shape=(), dtype=float64, numpy=22.8>)
(<tf.Tensor: id=2164, shape=(11,), dtype=float64, numpy=
array([ 12.   ,   6.   , 258.   , 110.   ,   3.08 ,   3.215,  19.44 ,
         1.   ,   0.   ,   3.   ,   1.   ])>, <tf.Tensor: id=2165, shape=(), dtype=float64, numpy=21.4>)
(<tf.Tensor: id=2168, shape=(11,), dtype=float64, numpy=
array([ 13.  ,   8.  , 360.  , 175.  

In [95]:
# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

In [114]:
def show_batch(dataset):
  for batch in dataset.take(1):
    for key, value in batch.items():
      print("{:20s}: {}".format(key,value))

In [115]:
def get_dataset(file_path, **kwargs):
  dataset = tf.data.experimental.make_csv_dataset(
      file_path,
      batch_size=5, # Artificially small to make examples easier to show.
      column_names=["","mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"],
      na_value="?",
      num_epochs=1, 
      **kwargs)
  return dataset


In [116]:
!head {test_file_path}

"","mpg","cyl","disp","hp","drat","wt","qsec","vs","am","gear","carb"
"Mazda RX4",21,6,160,110,3.9,2.62,16.46,0,1,4,4
"Mazda RX4 Wag",21,6,160,110,3.9,2.875,17.02,0,1,4,4
"Datsun 710",22.8,4,108,93,3.85,2.32,18.61,1,1,4,1
"Hornet 4 Drive",21.4,6,258,110,3.08,3.215,19.44,1,0,3,1
"Hornet Sportabout",18.7,8,360,175,3.15,3.44,17.02,0,0,3,2
"Valiant",18.1,6,225,105,2.76,3.46,20.22,1,0,3,1
"Duster 360",14.3,8,360,245,3.21,3.57,15.84,0,0,3,4
"Merc 240D",24.4,4,146.7,62,3.69,3.19,20,1,0,4,2
"Merc 230",22.8,4,140.8,95,3.92,3.15,22.9,1,0,4,2


In [117]:
testdata=get_dataset(test_file_path)

print(testdata.take(1))

show_batch(testdata)

<DatasetV1Adapter shapes: OrderedDict([(, (?,)), (mpg, (?,)), (cyl, (?,)), (disp, (?,)), (hp, (?,)), (drat, (?,)), (wt, (?,)), (qsec, (?,)), (vs, (?,)), (am, (?,)), (gear, (?,)), (carb, (?,))]), types: OrderedDict([(, tf.string), (mpg, tf.float32), (cyl, tf.int32), (disp, tf.float32), (hp, tf.int32), (drat, tf.float32), (wt, tf.float32), (qsec, tf.float32), (vs, tf.int32), (am, tf.int32), (gear, tf.int32), (carb, tf.int32)])>
                    : [b'Duster 360' b'Lotus Europa' b'Mazda RX4 Wag' b'Lincoln Continental'
 b'Ford Pantera L']
mpg                 : [14.3 30.4 21.  10.4 15.8]
cyl                 : [8 4 6 8 8]
disp                : [360.   95.1 160.  460.  351. ]
hp                  : [245 113 110 215 264]
drat                : [3.21 3.77 3.9  3.   4.22]
wt                  : [3.57  1.513 2.875 5.424 3.17 ]
qsec                : [15.84 16.9  17.02 17.82 14.5 ]
vs                  : [0 1 0 0 0]
am                  : [0 1 1 0 1]
gear                : [3 5 4 3 5]
carb             